CREATE TABLE countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10) NOT NULL,
    name VARCHAR(255),
    image_url VARCHAR(255),

    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_countries_code_active ON countries (code) WHERE deleted_at IS NULL;

INSERT INTO countries (code, name, image_url) VALUES
('VN', 'Vietnam', 'https://flagcdn.com/w320/vn.png'),
('US', 'United States', 'https://flagcdn.com/w320/us.png'),
('JP', 'Japan', 'https://flagcdn.com/w320/jp.png'),
('KR', 'South Korea', 'https://flagcdn.com/w320/kr.png'),
('FR', 'France', 'https://flagcdn.com/w320/fr.png'),
('DE', 'Germany', 'https://flagcdn.com/w320/de.png'),
('CN', 'China', 'https://flagcdn.com/w320/cn.png'),
('GB', 'United Kingdom', 'https://flagcdn.com/w320/gb.png');


ALTER TABLE users
ADD COLUMN gender VARCHAR(20),
ADD COLUMN date_of_birth DATE,
ADD COLUMN address VARCHAR(255),
ADD COLUMN country_id BIGINT;

ALTER TABLE users
ADD CONSTRAINT fk_users_country FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE SET NULL;

CREATE INDEX idx_users_country_id ON users(country_id);


CREATE TABLE candidate_profiles (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    bio TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE experiences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_profile_id BIGINT NOT NULL REFERENCES candidate_profiles(user_id) ON DELETE CASCADE,
    company VARCHAR(150) NOT NULL,
    position VARCHAR(150) NOT NULL,
    description TEXT,
    start_date DATE NOT NULL,
    end_date DATE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_experiences_candidate_profile_id ON experiences(candidate_profile_id);


CREATE TABLE educations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_profile_id BIGINT NOT NULL REFERENCES candidate_profiles(user_id) ON DELETE CASCADE,
    school VARCHAR(200) NOT NULL,
    description TEXT,
    major VARCHAR(150) NOT NULL,
    degree VARCHAR(20) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_educations_candidate_profile_id ON educations(candidate_profile_id);


CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logo VARCHAR(255),
    name VARCHAR(150) NOT NULL,
    type VARCHAR(20) NOT NULL,
    employee_size VARCHAR(20) NOT NULL,
    country_id BIGINT REFERENCES countries(id) ON DELETE SET NULL,
    description TEXT,
    tax_code VARCHAR(20) NOT NULL,

    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_companies_tax_code_active ON companies (tax_code) WHERE deleted_at IS NULL;
CREATE INDEX idx_companies_country_id ON companies(country_id);


CREATE TABLE employer_profiles (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(20) DEFAULT 'PENDING' NOT NULL,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    approved_by_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    approved_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_employer_profiles_company_id ON employer_profiles(company_id);
CREATE INDEX idx_employer_profiles_approved_by_id ON employer_profiles(approved_by_id);


CREATE TRIGGER trg_countries_updated_at BEFORE UPDATE ON countries FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_candidate_profiles_updated_at BEFORE UPDATE ON candidate_profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_experiences_updated_at BEFORE UPDATE ON experiences FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_educations_updated_at BEFORE UPDATE ON educations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_companies_updated_at BEFORE UPDATE ON companies FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_employer_profiles_updated_at BEFORE UPDATE ON employer_profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
