token.jwt.secret-key=YOUR_SECRET_KEY
# 900,000 ms = 15 minutes
token.access-token.ttl.millis=900000
token.refresh-token.ttl.days=7
oauth2.google.client-id=YOUR_GOOGLE_CLIENT_ID
oauth2.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
redis.host=localhost
redis.port=6379
redis.password=123456
# Async Task Executor Config
async.core-pool-size=5
async.max-pool-size=20
async.queue-capacity=500
async.thread-name-prefix=AsyncThread-
# Scheduled Task Scheduler Config
scheduled.pool-size=2
scheduled.thread-name-prefix=ScheduledThread-
# Common Shutdown Config
task.await-termination-seconds=60