hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.formatSql=true
hibernate.showSql=true
hibernate.connection.driverClass=com.mysql.cj.jdbc.Driver
db.host=localhost
db.port=3306
db.name=job_platform_db
db.user=YOUR_USER
db.password=YOUR_PASSWORD