token.jwt.secret-key=YOUR_SECRET_KEY
# 900,000 ms = 15 minutes
token.access-token.ttl.millis=900000
token.refresh-token.ttl.days=7
oauth2.google.client-id=YOUR_GOOGLE_CLIENT_ID
oauth2.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
redis.host=localhost
redis.port=6379
redis.password=123456
# Async Task Executor Config
async.core-pool-size=5
async.max-pool-size=20
async.queue-capacity=500
async.thread-name-prefix=AsyncThread-
# Scheduled Task Scheduler Config
scheduled.pool-size=2
scheduled.thread-name-prefix=ScheduledThread-
# Common Shutdown Config
task.await-termination-seconds=60
# Cloudinary config
cloud.name=datah8lgd
cloud.api-key=899758535566942
cloud.api-secret=nZAFBUzO70k6dkRT5FjUTY3nGII
# Supabase config
supabase.s3.project-id=thwoazsmtjwxkpiehnjy
supabase.s3.access-key=263b2b5ca50c8efd9200d7efb5b10ab9
supabase.s3.secret-key=27abbe5f92187363fa3b60397d95fb11711fee5e928683f90fb778e1ce3b2897
supabase.s3.bucket=django-job-platform
supabase.s3.region=ap-southeast-1
# Payment config
payment.stripe.public-key=pk_test_51THJP3RC9mczPN1RQatPZxZVHaeQBUJ6Cc5FMZWVT4YLeS38aOe5DdY2625XqfZz8eGepyTA46GbPbXteQQxGTS000vw4HnMOl
payment.stripe.secret-key=sk_test_51THJP3RC9mczPN1RVhQpxK9f17SqP4ZKFSe7sa7OyWpkNge8mOHd9JzaODPRCpz51wqzKSJ83xcAcu7H3i228sHr00p29QR1Gk
payment.stripe.webhook-secret=whsec_b778ffe3ef572bab3486b73d93f3e99dd387246d4198341b9ea0ac9a3c7f9e38
# App
app.jobs.expire-interval=1h
app.job.expiration-minutes=1440
app.ai.embed.host=localhost
app.ai.embed.port=8000
app.ai.embed.url=http://${app.ai.embed.host}:${app.ai.embed.port}/embed
app.ai.embed.timeout-ms=3000