token.jwt.secret-key=YOUR_SECRET_KEY
# 900,000 ms = 15 minutes
token.access-token.ttl.millis=900000
token.refresh-token.ttl.days=7
oauth2.google.client-id=YOUR_GOOGLE_CLIENT_ID
oauth2.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
redis.host=localhost
redis.port=6379
redis.password=123456