hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.connection.driverClass=com.p6spy.engine.spy.P6SpyDriver
hibernate.connection.url=jdbc:p6spy:postgresql://${db.host}:${db.port}/${db.name}?sslmode=disable
db.host=localhost
db.port=5432
db.name=job_platform_db
db.user=postgres
db.password=YOUR_PASSWORD