driverlist=org.postgresql.Driver
logMessageFormat=com.p6spy.engine.spy.appender.MultiLineFormat
appender=com.p6spy.engine.spy.appender.Slf4JLogger
executionThreshold=0
filter=false
excludecategories=info,debug,result,resultset