CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    parent_id BIGINT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories (id) ON DELETE CASCADE
);

CREATE TRIGGER trg_categories_updated_at BEFORE UPDATE ON categories FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE INDEX idx_categories_parent_id ON categories(parent_id);


CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT,
    company_id BIGINT NOT NULL,
    address_id BIGINT NOT NULL,

    employment_type VARCHAR(20) NOT NULL DEFAULT 'INTERNSHIP',
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    experience_level VARCHAR(20),

    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    requirements TEXT NOT NULL,
    benefit TEXT NOT NULL,

    salary_min NUMERIC(15, 2),
    salary_max NUMERIC(15, 2),
    salary_currency VARCHAR(10) NOT NULL DEFAULT 'VND',

    boost_score INTEGER NOT NULL DEFAULT 0,
    published_at TIMESTAMPTZ,
    expired_at TIMESTAMPTZ,

    search_vector TSVECTOR,

    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_jobs_category FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL,
    CONSTRAINT fk_jobs_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE,
    CONSTRAINT fk_jobs_address FOREIGN KEY (address_id) REFERENCES addresses (id) ON DELETE RESTRICT
);

CREATE TRIGGER trg_jobs_updated_at BEFORE UPDATE ON jobs FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX idx_jobs_category_id ON jobs(category_id);
CREATE INDEX idx_jobs_company_id ON jobs(company_id);
CREATE INDEX idx_jobs_address_id ON jobs(address_id);


CREATE INDEX jobs_search_vector_idx ON jobs USING GIN (search_vector) WHERE deleted_at IS NULL;

CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE OR REPLACE FUNCTION update_jobs_search_vector()
RETURNS TRIGGER AS $$
DECLARE
    v_company_name TEXT;
BEGIN
    SELECT name INTO v_company_name
    FROM companies
    WHERE id = NEW.company_id;

    NEW.search_vector :=
        setweight(to_tsvector('simple', unaccent(COALESCE(NEW.title, ''))), 'A') ||
        setweight(to_tsvector('simple', unaccent(COALESCE(v_company_name, ''))), 'A') ||
        setweight(to_tsvector('simple', unaccent(COALESCE(NEW.description, ''))), 'B') ||
        setweight(to_tsvector('simple', unaccent(COALESCE(NEW.requirements, ''))), 'C');

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


DROP TRIGGER IF EXISTS trg_jobs_search_vector_update ON jobs;

CREATE TRIGGER trg_jobs_search_vector_update
BEFORE INSERT OR UPDATE OF title, description, requirements, company_id
ON jobs
FOR EACH ROW
EXECUTE FUNCTION update_jobs_search_vector();