CREATE TABLE candidate_cvs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_profile_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    file_url VARCHAR(255) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_candidate_cvs_profile FOREIGN KEY (candidate_profile_id) REFERENCES candidate_profiles (user_id) ON DELETE CASCADE
);

CREATE TRIGGER trg_candidate_cvs_updated_at BEFORE UPDATE ON candidate_cvs FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE INDEX idx_candidate_cvs_profile_id ON candidate_cvs(candidate_profile_id);


CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_profile_id BIGINT NOT NULL,
    job_id BIGINT NOT NULL,
    cv_file_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    expected_salary NUMERIC(15, 2) CHECK (expected_salary >= 0),
    note TEXT,

    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_applications_profile FOREIGN KEY (candidate_profile_id) REFERENCES candidate_profiles (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_applications_job FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE,
    CONSTRAINT fk_applications_cv FOREIGN KEY (cv_file_id) REFERENCES candidate_cvs (id) ON DELETE SET NULL,

    CONSTRAINT uq_applications_profile_job UNIQUE (candidate_profile_id, job_id)
);

CREATE TRIGGER trg_applications_updated_at BEFORE UPDATE ON applications FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


CREATE INDEX idx_applications_profile_id ON applications(candidate_profile_id);
CREATE INDEX idx_applications_job_id ON applications(job_id);
CREATE INDEX idx_applications_cv_file_id ON applications(cv_file_id);