CREATE TABLE review_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    old_status VARCHAR(20),
    new_status VARCHAR(20),
    reason TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_review_applications_application FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE CASCADE,
    CONSTRAINT fk_review_applications_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TRIGGER trg_review_applications_updated_at BEFORE UPDATE ON review_applications FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE INDEX idx_review_applications_application_id ON review_applications(application_id);
CREATE INDEX idx_review_applications_user_id ON review_applications(user_id);