INSERT INTO jobs (
    category_id,
    company_id,
    address_id,
    employment_type,
    status,
    experience_level,
    title,
    description,
    requirements,
    benefit,
    salary_min,
    salary_max,
    salary_currency,
    boost_score,
    published_at,
    expired_at
) VALUES
(2, 1, 1, 'FULL_TIME', 'PUBLISHED', 'JUNIOR',
 'Golang Backend Engineer',
 'Tham gia phát triển các hệ thống microservices hiệu năng cao, tối ưu hóa database và xây dựng các tính năng real-time.',
 'Có ít nhất 1 năm kinh nghiệm với Golang. Thành thạo SQL (PostgreSQL/MySQL) và Redis. Biết về Docker là một lợi thế.',
 'Lương thưởng tháng 13, bonus theo dự án. Bảo hiểm đầy đủ. Lộ trình thăng tiến rõ ràng.',
 15000000.00, 25000000.00, 'VND', 10, NOW(), NOW() + INTERVAL '30 days'),

(9, 1, 1, 'INTERNSHIP', 'PUBLISHED', 'INTERN',
 'Thực tập sinh AI & Machine Learning',
 'Hỗ trợ đội ngũ nghiên cứu thu thập dữ liệu, huấn luyện các mô hình xử lý ngôn ngữ tự nhiên và thị giác máy tính (Computer Vision).',
 'Sinh viên năm cuối chuyên ngành CNTT, Khoa học dữ liệu. Có kiến thức cơ bản về Python, PyTorch hoặc TensorFlow.',
 'Trợ cấp thực tập hấp dẫn. Được hướng dẫn bởi Senior giàu kinh nghiệm. Cơ hội trở thành nhân viên chính thức.',
 4000000.00, 6000000.00, 'VND', 0, NOW(), NOW() + INTERVAL '45 days'),

(2, 2, 1, 'FULL_TIME', 'PUBLISHED', 'SENIOR',
 'Senior Java Developer (Spring Boot)',
 'Chịu trách nhiệm kiến trúc và phát triển cấu trúc backend cho các hệ thống enterprise lớn của khách hàng quốc tế.',
 'Trên 5 năm kinh nghiệm làm việc với Java/Spring Boot. Khả năng thiết kế hệ thống tốt, thành thạo CI/CD và kiến trúc Microservices.',
 'Môi trường làm việc quốc tế. Gói bảo hiểm sức khỏe cao cấp. Hỗ trợ học và thi các chứng chỉ công nghệ.',
 35000000.00, 55000000.00, 'VND', 20, NOW(), NOW() + INTERVAL '30 days'),

(6, 2, 1, 'FULL_TIME', 'PUBLISHED', 'FRESHER',
 'Fresher Automation Test Engineer',
 'Tham gia viết test case, xây dựng kịch bản kiểm thử tự động cho các sản phẩm web và mobile ứng dụng.',
 'Nắm vững kiến thức cơ bản về OOP. Biết sử dụng Selenium, Java hoặc Python để viết script test là lợi thế lớn. Tiếng Anh giao tiếp cơ bản.',
 'Được đào tạo bài bản trong 2 tháng đầu nhận việc. Thưởng cuối năm. Tham gia các hoạt động teambuilding hoành tráng.',
 10000000.00, 14000000.00, 'VND', 5, NOW(), NOW() + INTERVAL '30 days'),

(13, 3, 2, 'FULL_TIME', 'PUBLISHED', 'MIDDLE',
 'Game Developer (C++/Unity)',
 'Phát triển và tối ưu hóa các tính năng gameplay, xử lý logic real-time và đồng bộ hóa dữ liệu mạng cho các tựa game mobile.',
 'Có từ 2-3 năm kinh nghiệm phát triển game. Thành thạo C++ hoặc C#. Có tư duy tốt về cấu trúc dữ liệu và giải thuật.',
 'Làm việc tại campus hiện đại bậc nhất. Thưởng performance định kỳ. Cơm trưa và chỗ đậu xe miễn phí.',
 22000000.00, 35000000.00, 'VND', 15, NOW(), NOW() + INTERVAL '30 days'),

(10, 3, 2, 'FULL_TIME', 'PUBLISHED', 'LEAD',
 'Cloud DevOps Tech Lead',
 'Dẫn dắt đội ngũ vận hành hệ thống hạ tầng Cloud, thiết kế kiến trúc hạ tầng chịu tải lớn và tự động hóa quy trình triển khai.',
 'Có kinh nghiệm Lead đội ngũ. Chuyên gia về AWS/GCP, Kubernetes (K8s), Docker và các công cụ CI/CD (Jenkins, GitLab CI).',
 'Mức lương cạnh tranh kèm theo cổ phiếu thưởng (ESOP). Nghỉ dưỡng hàng năm. Môi trường công nghệ hàng đầu.',
 60000000.00, 90000000.00, 'VND', 30, NOW(), NOW() + INTERVAL '15 days'),

(4, 4, 3, 'FULL_TIME', 'PUBLISHED', 'MIDDLE',
 'Data Analyst (E-commerce)',
 'Phân tích dữ liệu hành vi người dùng, doanh số bán hàng để đưa ra các báo cáo chiến lược giúp tối ưu hóa hệ thống vận hành và marketing.',
 'Tối thiểu 2 năm kinh nghiệm làm Data Analyst. Sử dụng thành thạo SQL, Python/R và các công cụ Visualization (Tableau, PowerBI).',
 'Mua hàng Tiki với giá ưu đãi. Được làm việc với lượng data cực lớn (Big Data). Thưởng tháng 13+.',
 18000000.00, 28000000.00, 'VND', 12, NOW(), NOW() + INTERVAL '30 days'),

(7, 4, 3, 'CONTRACT', 'PUBLISHED', 'SENIOR',
 'Senior UI/UX Designer',
 'Thiết kế giao diện và trải nghiệm người dùng trên cả hai nền tảng Web và Mobile App nhằm nâng cao tỷ lệ chuyển đổi đổi đơn hàng.',
 'Trên 4 năm kinh nghiệm chuyên sâu về UI/UX. Thành thạo Figma, Adobe Creative Suite. Có portfolio sản phẩm thực tế ấn tượng.',
 'Lương thỏa thuận theo năng lực. Môi trường làm việc trẻ trung, sáng tạo, không áp đặt.',
 30000000.00, 45000000.00, 'VND', 8, NOW(), NOW() + INTERVAL '45 days'),

(2, 5, 4, 'FULL_TIME', 'PUBLISHED', 'MIDDLE',
 'Fullstack Developer (Python/ReactJS)',
 'Phát triển toàn diện các ứng dụng web ứng dụng Agile/Scrum, làm việc trực tiếp với khách hàng nước ngoài.',
 'Kinh nghiệm vững chắc với Python (Django/Flask) ở Backend và ReactJS ở Frontend. Giao tiếp tiếng Anh lưu loát.',
 'Làm việc 5 ngày/tuần (Nghỉ T7, CN). Miễn phí lớp học tiếng Anh/tiếng Pháp tại công ty. Đi du lịch nước ngoài theo dự án.',
 25000000.00, 40000000.00, 'VND', 10, NOW(), NOW() + INTERVAL '60 days'),

(8, 5, 4, 'FULL_TIME', 'PUBLISHED', 'LEAD',
 'IT Scrum Master / Project Manager',
 'Quản lý tiến độ dự án phần mềm, điều phối các sprint và hỗ trợ tháo gỡ khó khăn cho các đội ngũ phát triển theo mô hình Scrum.',
 'Có chứng chỉ Scrum Master (PSM/CSM). Ít nhất 3 năm kinh nghiệm quản lý dự án phần mềm. Khả năng giao tiếp và xử lý tình huống tốt.',
 'Môi trường làm việc chuẩn Thụy Sĩ. Bảo hiểm sức khỏe cho bản thân và gia đình. Cơ hội onsite châu Âu.',
 40000000.00, 65000000.00, 'VND', 15, NOW(), NOW() + INTERVAL '30 days'),

(5, 6, 5, 'FULL_TIME', 'PUBLISHED', 'SENIOR',
 'Cyber Security Engineer',
 'Giám sát an ninh mạng, thực hiện các biện pháp đánh giá lỗ hổng bảo mật (Penetration Testing) và ứng phó sự cố an toàn thông tin.',
 'Có kinh nghiệm về Network Security, Pentest Web/API. Có các chứng chỉ như CEH, CompTIA Security+, CISSP là lợi thế lớn.',
 'Được làm việc trong các dự án bảo mật quy mô lớn. Xét tăng lương hàng năm. Thưởng các ngày lễ tết.',
 30000000.00, 50000000.00, 'VND', 18, NOW(), NOW() + INTERVAL '30 days'),

(11, 6, 5, 'FULL_TIME', 'PUBLISHED', 'JUNIOR',
 'IT Support / Helpdesk Engineer',
 'Cài đặt, cấu hình phần cứng, phần mềm hệ thống máy tính văn phòng và hỗ trợ kỹ thuật nội bộ cho nhân viên công ty.',
 'Tốt nghiệp cao đẳng/đại học chuyên ngành CNTT. Có kiến thức cơ bản về hệ điều hành Windows/MacOS, cấu hình Network cơ bản.',
 'Môi trường thân thiện, sếp tâm lý. Cung cấp đầy đủ thiết bị làm việc hiện đại. Trà, cafe tự do tại pantry.',
 10000000.00, 15000000.00, 'VND', 2, NOW(), NOW() + INTERVAL '30 days');