INSERT INTO countries (code, name, image_url) VALUES
('AI', 'Anguilla', 'https://flagcdn.com/w320/ai.png'),
('GT', 'Republic of Guatemala', 'https://flagcdn.com/w320/gt.png'),
('GM', 'Republic of the Gambia', 'https://flagcdn.com/w320/gm.png'),
('MX', 'United Mexican States', 'https://flagcdn.com/w320/mx.png'),
('MW', 'Republic of Malawi', 'https://flagcdn.com/w320/mw.png'),
('PN', 'Pitcairn Group of Islands', 'https://flagcdn.com/w320/pn.png'),
('AR', 'Argentine Republic', 'https://flagcdn.com/w320/ar.png'),
('GU', 'Guam', 'https://flagcdn.com/w320/gu.png'),
('BG', 'Republic of Bulgaria', 'https://flagcdn.com/w320/bg.png'),
('DM', 'Commonwealth of Dominica', 'https://flagcdn.com/w320/dm.png'),
('GB', 'United Kingdom of Great Britain and Northern Ireland', 'https://flagcdn.com/w320/gb.png'),
('FM', 'Federated States of Micronesia', 'https://flagcdn.com/w320/fm.png'),
('PS', 'State of Palestine', 'https://flagcdn.com/w320/ps.png'),
('CW', 'Country of Curaçao', 'https://flagcdn.com/w320/cw.png'),
('RW', 'Republic of Rwanda', 'https://flagcdn.com/w320/rw.png'),
('HK', 'Hong Kong Special Administrative Region of the People''s Republic of China', 'https://flagcdn.com/w320/hk.png'),
('UZ', 'Republic of Uzbekistan', 'https://flagcdn.com/w320/uz.png'),
('CN', 'People''s Republic of China', 'https://flagcdn.com/w320/cn.png'),
('CY', 'Republic of Cyprus', 'https://flagcdn.com/w320/cy.png'),
('AW', 'Aruba', 'https://flagcdn.com/w320/aw.png'),
('RE', 'Réunion Island', 'https://flagcdn.com/w320/re.png'),
('KR', 'Republic of Korea', 'https://flagcdn.com/w320/kr.png'),
('AQ', 'Antarctica', 'https://flagcdn.com/w320/aq.png'),
('SO', 'Federal Republic of Somalia', 'https://flagcdn.com/w320/so.png'),
('LB', 'Lebanese Republic', 'https://flagcdn.com/w320/lb.png'),
('GN', 'Republic of Guinea', 'https://flagcdn.com/w320/gn.png'),
('TJ', 'Republic of Tajikistan', 'https://flagcdn.com/w320/tj.png'),
('MY', 'Malaysia', 'https://flagcdn.com/w320/my.png'),
('KP', 'Democratic People''s Republic of Korea', 'https://flagcdn.com/w320/kp.png'),
('SL', 'Republic of Sierra Leone', 'https://flagcdn.com/w320/sl.png'),
('BJ', 'Republic of Benin', 'https://flagcdn.com/w320/bj.png'),
('IT', 'Italian Republic', 'https://flagcdn.com/w320/it.png'),
('TT', 'Republic of Trinidad and Tobago', 'https://flagcdn.com/w320/tt.png'),
('SA', 'Kingdom of Saudi Arabia', 'https://flagcdn.com/w320/sa.png'),
('CR', 'Republic of Costa Rica', 'https://flagcdn.com/w320/cr.png'),
('RS', 'Republic of Serbia', 'https://flagcdn.com/w320/rs.png'),
('TK', 'Tokelau', 'https://flagcdn.com/w320/tk.png'),
('MN', 'Mongolia', 'https://flagcdn.com/w320/mn.png'),
('BN', 'Nation of Brunei, Abode of Peace', 'https://flagcdn.com/w320/bn.png'),
('HU', 'Hungary', 'https://flagcdn.com/w320/hu.png'),
('MZ', 'Republic of Mozambique', 'https://flagcdn.com/w320/mz.png'),
('KI', 'Independent and Sovereign Republic of Kiribati', 'https://flagcdn.com/w320/ki.png'),
('HT', 'Republic of Haiti', 'https://flagcdn.com/w320/ht.png'),
('KH', 'Kingdom of Cambodia', 'https://flagcdn.com/w320/kh.png'),
('EG', 'Arab Republic of Egypt', 'https://flagcdn.com/w320/eg.png'),
('TM', 'Turkmenistan', 'https://flagcdn.com/w320/tm.png'),
('OM', 'Sultanate of Oman', 'https://flagcdn.com/w320/om.png'),
('JM', 'Jamaica', 'https://flagcdn.com/w320/jm.png'),
('AZ', 'Republic of Azerbaijan', 'https://flagcdn.com/w320/az.png'),
('SK', 'Slovak Republic', 'https://flagcdn.com/w320/sk.png'),
('BY', 'Republic of Belarus', 'https://flagcdn.com/w320/by.png'),
('VN', 'Socialist Republic of Vietnam', 'https://flagcdn.com/w320/vn.png'),
('VI', 'Virgin Islands of the United States', 'https://flagcdn.com/w320/vi.png'),
('GI', 'Gibraltar', 'https://flagcdn.com/w320/gi.png'),
('SX', 'Sint Maarten', 'https://flagcdn.com/w320/sx.png'),
('AX', 'Åland Islands', 'https://flagcdn.com/w320/ax.png'),
('SY', 'Syrian Arab Republic', 'https://flagcdn.com/w320/sy.png'),
('MQ', 'Martinique', 'https://flagcdn.com/w320/mq.png'),
('GL', 'Greenland', 'https://flagcdn.com/w320/gl.png'),
('HN', 'Republic of Honduras', 'https://flagcdn.com/w320/hn.png'),
('TN', 'Tunisian Republic', 'https://flagcdn.com/w320/tn.png'),
('KM', 'Union of the Comoros', 'https://flagcdn.com/w320/km.png'),
('SI', 'Republic of Slovenia', 'https://flagcdn.com/w320/si.png'),
('CH', 'Swiss Confederation', 'https://flagcdn.com/w320/ch.png'),
('GG', 'Bailiwick of Guernsey', 'https://flagcdn.com/w320/gg.png'),
('MM', 'Republic of the Union of Myanmar', 'https://flagcdn.com/w320/mm.png'),
('PY', 'Republic of Paraguay', 'https://flagcdn.com/w320/py.png'),
('BQ', 'Bonaire, Sint Eustatius and Saba', 'https://flagcdn.com/w320/bq.png'),
('BB', 'Barbados', 'https://flagcdn.com/w320/bb.png'),
('MO', 'Macao Special Administrative Region of the People''s Republic of China', 'https://flagcdn.com/w320/mo.png'),
('JO', 'Hashemite Kingdom of Jordan', 'https://flagcdn.com/w320/jo.png'),
('LA', 'Lao People''s Democratic Republic', 'https://flagcdn.com/w320/la.png'),
('TG', 'Togolese Republic', 'https://flagcdn.com/w320/tg.png'),
('MA', 'Kingdom of Morocco', 'https://flagcdn.com/w320/ma.png'),
('PR', 'Commonwealth of Puerto Rico', 'https://flagcdn.com/w320/pr.png'),
('GF', 'Guiana', 'https://flagcdn.com/w320/gf.png'),
('PM', 'Saint Pierre and Miquelon', 'https://flagcdn.com/w320/pm.png'),
('MF', 'Saint Martin', 'https://flagcdn.com/w320/mf.png'),
('EE', 'Republic of Estonia', 'https://flagcdn.com/w320/ee.png'),
('ID', 'Republic of Indonesia', 'https://flagcdn.com/w320/id.png'),
('SC', 'Republic of Seychelles', 'https://flagcdn.com/w320/sc.png'),
('ML', 'Republic of Mali', 'https://flagcdn.com/w320/ml.png'),
('TL', 'Democratic Republic of Timor-Leste', 'https://flagcdn.com/w320/tl.png'),
('BR', 'Federative Republic of Brazil', 'https://flagcdn.com/w320/br.png'),
('GH', 'Republic of Ghana', 'https://flagcdn.com/w320/gh.png'),
('KE', 'Republic of Kenya', 'https://flagcdn.com/w320/ke.png'),
('IS', 'Iceland', 'https://flagcdn.com/w320/is.png'),
('MG', 'Republic of Madagascar', 'https://flagcdn.com/w320/mg.png'),
('BD', 'People''s Republic of Bangladesh', 'https://flagcdn.com/w320/bd.png'),
('CD', 'Democratic Republic of the Congo', 'https://flagcdn.com/w320/cd.png'),
('ZW', 'Republic of Zimbabwe', 'https://flagcdn.com/w320/zw.png'),
('PF', 'French Polynesia', 'https://flagcdn.com/w320/pf.png'),
('TR', 'Republic of Turkey', 'https://flagcdn.com/w320/tr.png'),
('CV', 'Republic of Cabo Verde', 'https://flagcdn.com/w320/cv.png'),
('DO', 'Dominican Republic', 'https://flagcdn.com/w320/do.png'),
('BS', 'Commonwealth of the Bahamas', 'https://flagcdn.com/w320/bs.png'),
('DE', 'Federal Republic of Germany', 'https://flagcdn.com/w320/de.png'),
('SR', 'Republic of Suriname', 'https://flagcdn.com/w320/sr.png'),
('TO', 'Kingdom of Tonga', 'https://flagcdn.com/w320/to.png'),
('IO', 'British Indian Ocean Territory', 'https://flagcdn.com/w320/io.png'),
('LC', 'Saint Lucia', 'https://flagcdn.com/w320/lc.png'),
('IE', 'Republic of Ireland', 'https://flagcdn.com/w320/ie.png'),
('VA', 'Vatican City State', 'https://flagcdn.com/w320/va.png'),
('CO', 'Republic of Colombia', 'https://flagcdn.com/w320/co.png'),
('PT', 'Portuguese Republic', 'https://flagcdn.com/w320/pt.png'),
('FO', 'Faroe Islands', 'https://flagcdn.com/w320/fo.png'),
('ST', 'Democratic Republic of São Tomé and Príncipe', 'https://flagcdn.com/w320/st.png'),
('MP', 'Commonwealth of the Northern Mariana Islands', 'https://flagcdn.com/w320/mp.png'),
('JE', 'Bailiwick of Jersey', 'https://flagcdn.com/w320/je.png'),
('YT', 'Department of Mayotte', 'https://flagcdn.com/w320/yt.png'),
('YE', 'Republic of Yemen', 'https://flagcdn.com/w320/ye.png'),
('NG', 'Federal Republic of Nigeria', 'https://flagcdn.com/w320/ng.png'),
('AF', 'Islamic Republic of Afghanistan', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png'),
('BW', 'Republic of Botswana', 'https://flagcdn.com/w320/bw.png'),
('IM', 'Isle of Man', 'https://flagcdn.com/w320/im.png'),
('SV', 'Republic of El Salvador', 'https://flagcdn.com/w320/sv.png'),
('UG', 'Republic of Uganda', 'https://flagcdn.com/w320/ug.png'),
('AD', 'Principality of Andorra', 'https://flagcdn.com/w320/ad.png'),
('TC', 'Turks and Caicos Islands', 'https://flagcdn.com/w320/tc.png'),
('TD', 'Republic of Chad', 'https://flagcdn.com/w320/td.png'),
('FI', 'Republic of Finland', 'https://flagcdn.com/w320/fi.png'),
('RU', 'Russian Federation', 'https://flagcdn.com/w320/ru.png'),
('KZ', 'Republic of Kazakhstan', 'https://flagcdn.com/w320/kz.png'),
('SJ', 'Svalbard og Jan Mayen', 'https://flagcdn.com/w320/sj.png'),
('VE', 'Bolivarian Republic of Venezuela', 'https://flagcdn.com/w320/ve.png'),
('MC', 'Principality of Monaco', 'https://flagcdn.com/w320/mc.png'),
('SN', 'Republic of Senegal', 'https://flagcdn.com/w320/sn.png'),
('NP', 'Federal Democratic Republic of Nepal', 'https://flagcdn.com/w320/np.png'),
('AE', 'United Arab Emirates', 'https://flagcdn.com/w320/ae.png'),
('TW', 'Republic of China (Taiwan)', 'https://flagcdn.com/w320/tw.png'),
('NC', 'New Caledonia', 'https://flagcdn.com/w320/nc.png'),
('BO', 'Plurinational State of Bolivia', 'https://flagcdn.com/w320/bo.png'),
('CL', 'Republic of Chile', 'https://flagcdn.com/w320/cl.png'),
('CI', 'Republic of Côte d''Ivoire', 'https://flagcdn.com/w320/ci.png'),
('LY', 'State of Libya', 'https://flagcdn.com/w320/ly.png'),
('PE', 'Republic of Peru', 'https://flagcdn.com/w320/pe.png'),
('CA', 'Canada', 'https://flagcdn.com/w320/ca.png'),
('FR', 'French Republic', 'https://flagcdn.com/w320/fr.png'),
('DJ', 'Republic of Djibouti', 'https://flagcdn.com/w320/dj.png'),
('BI', 'Republic of Burundi', 'https://flagcdn.com/w320/bi.png'),
('XK', 'Republic of Kosovo', 'https://flagcdn.com/w320/xk.png'),
('DK', 'Kingdom of Denmark', 'https://flagcdn.com/w320/dk.png'),
('GR', 'Hellenic Republic', 'https://flagcdn.com/w320/gr.png'),
('CZ', 'Czech Republic', 'https://flagcdn.com/w320/cz.png'),
('ER', 'State of Eritrea', 'https://flagcdn.com/w320/er.png'),
('NA', 'Republic of Namibia', 'https://flagcdn.com/w320/na.png'),
('VG', 'Virgin Islands', 'https://flagcdn.com/w320/vg.png'),
('IR', 'Islamic Republic of Iran', 'https://flagcdn.com/w320/ir.png'),
('GQ', 'Republic of Equatorial Guinea', 'https://flagcdn.com/w320/gq.png'),
('MR', 'Islamic Republic of Mauritania', 'https://flagcdn.com/w320/mr.png'),
('BH', 'Kingdom of Bahrain', 'https://flagcdn.com/w320/bh.png'),
('CC', 'Territory of the Cocos (Keeling) Islands', 'https://flagcdn.com/w320/cc.png'),
('ET', 'Federal Democratic Republic of Ethiopia', 'https://flagcdn.com/w320/et.png'),
('ZM', 'Republic of Zambia', 'https://flagcdn.com/w320/zm.png'),
('BA', 'Bosnia and Herzegovina', 'https://flagcdn.com/w320/ba.png'),
('FK', 'Falkland Islands', 'https://flagcdn.com/w320/fk.png'),
('GD', 'Grenada', 'https://flagcdn.com/w320/gd.png'),
('TH', 'Kingdom of Thailand', 'https://flagcdn.com/w320/th.png'),
('RO', 'Romania', 'https://flagcdn.com/w320/ro.png'),
('VC', 'Saint Vincent and the Grenadines', 'https://flagcdn.com/w320/vc.png'),
('LR', 'Republic of Liberia', 'https://flagcdn.com/w320/lr.png'),
('US', 'United States of America', 'https://flagcdn.com/w320/us.png'),
('SS', 'Republic of South Sudan', 'https://flagcdn.com/w320/ss.png'),
('BV', 'Bouvet Island', 'https://flagcdn.com/w320/bv.png'),
('AM', 'Republic of Armenia', 'https://flagcdn.com/w320/am.png'),
('JP', 'Japan', 'https://flagcdn.com/w320/jp.png'),
('PK', 'Islamic Republic of Pakistan', 'https://flagcdn.com/w320/pk.png'),
('SZ', 'Kingdom of Eswatini', 'https://flagcdn.com/w320/sz.png'),
('LI', 'Principality of Liechtenstein', 'https://flagcdn.com/w320/li.png'),
('IL', 'State of Israel', 'https://flagcdn.com/w320/il.png'),
('AS', 'American Samoa', 'https://flagcdn.com/w320/as.png'),
('LK', 'Democratic Socialist Republic of Sri Lanka', 'https://flagcdn.com/w320/lk.png'),
('GS', 'South Georgia and the South Sandwich Islands', 'https://flagcdn.com/w320/gs.png'),
('AL', 'Republic of Albania', 'https://flagcdn.com/w320/al.png'),
('DZ', 'People''s Democratic Republic of Algeria', 'https://flagcdn.com/w320/dz.png'),
('UA', 'Ukraine', 'https://flagcdn.com/w320/ua.png'),
('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'https://flagcdn.com/w320/sh.png'),
('HM', 'Heard Island and McDonald Islands', 'https://flagcdn.com/w320/hm.png'),
('SM', 'Republic of San Marino', 'https://flagcdn.com/w320/sm.png'),
('CU', 'Republic of Cuba', 'https://flagcdn.com/w320/cu.png'),
('NR', 'Republic of Nauru', 'https://flagcdn.com/w320/nr.png'),
('ES', 'Kingdom of Spain', 'https://flagcdn.com/w320/es.png'),
('KW', 'State of Kuwait', 'https://flagcdn.com/w320/kw.png'),
('MS', 'Montserrat', 'https://flagcdn.com/w320/ms.png'),
('MU', 'Republic of Mauritius', 'https://flagcdn.com/w320/mu.png'),
('SE', 'Kingdom of Sweden', 'https://flagcdn.com/w320/se.png'),
('AU', 'Commonwealth of Australia', 'https://flagcdn.com/w320/au.png'),
('CM', 'Republic of Cameroon', 'https://flagcdn.com/w320/cm.png'),
('EC', 'Republic of Ecuador', 'https://flagcdn.com/w320/ec.png'),
('QA', 'State of Qatar', 'https://flagcdn.com/w320/qa.png'),
('MH', 'Republic of the Marshall Islands', 'https://flagcdn.com/w320/mh.png'),
('PL', 'Republic of Poland', 'https://flagcdn.com/w320/pl.png'),
('KY', 'Cayman Islands', 'https://flagcdn.com/w320/ky.png'),
('ZA', 'Republic of South Africa', 'https://flagcdn.com/w320/za.png'),
('WF', 'Territory of the Wallis and Futuna Islands', 'https://flagcdn.com/w320/wf.png'),
('WS', 'Independent State of Samoa', 'https://flagcdn.com/w320/ws.png'),
('NL', 'Kingdom of the Netherlands', 'https://flagcdn.com/w320/nl.png'),
('EH', 'Sahrawi Arab Democratic Republic', 'https://flagcdn.com/w320/eh.png'),
('ME', 'Montenegro', 'https://flagcdn.com/w320/me.png'),
('BT', 'Kingdom of Bhutan', 'https://flagcdn.com/w320/bt.png'),
('MT', 'Republic of Malta', 'https://flagcdn.com/w320/mt.png'),
('VU', 'Republic of Vanuatu', 'https://flagcdn.com/w320/vu.png'),
('TZ', 'United Republic of Tanzania', 'https://flagcdn.com/w320/tz.png'),
('NZ', 'New Zealand', 'https://flagcdn.com/w320/nz.png'),
('PW', 'Republic of Palau', 'https://flagcdn.com/w320/pw.png'),
('PA', 'Republic of Panama', 'https://flagcdn.com/w320/pa.png'),
('TV', 'Tuvalu', 'https://flagcdn.com/w320/tv.png'),
('FJ', 'Republic of Fiji', 'https://flagcdn.com/w320/fj.png'),
('NI', 'Republic of Nicaragua', 'https://flagcdn.com/w320/ni.png'),
('KG', 'Kyrgyz Republic', 'https://flagcdn.com/w320/kg.png'),
('TF', 'Territory of the French Southern and Antarctic Lands', 'https://flagcdn.com/w320/tf.png'),
('LV', 'Republic of Latvia', 'https://flagcdn.com/w320/lv.png'),
('GE', 'Georgia', 'https://flagcdn.com/w320/ge.png'),
('LU', 'Grand Duchy of Luxembourg', 'https://flagcdn.com/w320/lu.png'),
('AT', 'Republic of Austria', 'https://flagcdn.com/w320/at.png'),
('MK', 'Republic of North Macedonia', 'https://flagcdn.com/w320/mk.png'),
('BL', 'Collectivity of Saint Barthélemy', 'https://flagcdn.com/w320/bl.png'),
('CX', 'Territory of Christmas Island', 'https://flagcdn.com/w320/cx.png'),
('SB', 'Solomon Islands', 'https://flagcdn.com/w320/sb.png'),
('AG', 'Antigua and Barbuda', 'https://flagcdn.com/w320/ag.png'),
('IQ', 'Republic of Iraq', 'https://flagcdn.com/w320/iq.png'),
('MD', 'Republic of Moldova', 'https://flagcdn.com/w320/md.png'),
('NF', 'Territory of Norfolk Island', 'https://flagcdn.com/w320/nf.png'),
('CG', 'Republic of the Congo', 'https://flagcdn.com/w320/cg.png'),
('NU', 'Niue', 'https://flagcdn.com/w320/nu.png'),
('LT', 'Republic of Lithuania', 'https://flagcdn.com/w320/lt.png'),
('NE', 'Republic of Niger', 'https://flagcdn.com/w320/ne.png'),
('GY', 'Co-operative Republic of Guyana', 'https://flagcdn.com/w320/gy.png'),
('BM', 'Bermuda', 'https://flagcdn.com/w320/bm.png'),
('GA', 'Gabonese Republic', 'https://flagcdn.com/w320/ga.png'),
('CK', 'Cook Islands', 'https://flagcdn.com/w320/ck.png'),
('AO', 'Republic of Angola', 'https://flagcdn.com/w320/ao.png'),
('NO', 'Kingdom of Norway', 'https://flagcdn.com/w320/no.png'),
('GP', 'Guadeloupe', 'https://flagcdn.com/w320/gp.png'),
('MV', 'Republic of the Maldives', 'https://flagcdn.com/w320/mv.png'),
('BE', 'Kingdom of Belgium', 'https://flagcdn.com/w320/be.png'),
('HR', 'Republic of Croatia', 'https://flagcdn.com/w320/hr.png'),
('BZ', 'Belize', 'https://flagcdn.com/w320/bz.png'),
('KN', 'Federation of Saint Christopher and Nevis', 'https://flagcdn.com/w320/kn.png'),
('SG', 'Republic of Singapore', 'https://flagcdn.com/w320/sg.png'),
('LS', 'Kingdom of Lesotho', 'https://flagcdn.com/w320/ls.png'),
('UY', 'Oriental Republic of Uruguay', 'https://flagcdn.com/w320/uy.png'),
('BF', 'Burkina Faso', 'https://flagcdn.com/w320/bf.png'),
('IN', 'Republic of India', 'https://flagcdn.com/w320/in.png'),
('PH', 'Republic of the Philippines', 'https://flagcdn.com/w320/ph.png'),
('CF', 'Central African Republic', 'https://flagcdn.com/w320/cf.png'),
('SD', 'Republic of the Sudan', 'https://flagcdn.com/w320/sd.png'),
('GW', 'Republic of Guinea-Bissau', 'https://flagcdn.com/w320/gw.png'),
('PG', 'Independent State of Papua New Guinea', 'https://flagcdn.com/w320/pg.png'),
('UM', 'United States Minor Outlying Islands', 'https://flagcdn.com/w320/um.png');